### ISSUE TITLE
Error in random cases with X11DISPLAY

### ISSUE THREAD

**Issue by Doc94** [gkopff/logback-raygun#19]
i have a issue with a "console app" running into Heroku.
in any cases i get this issue when send a LOG.

`2019-04-07T18:05:36.006421+00:00 app[worker.1]: Apr 07, 2019 2:05:36 PM com.mindscapehq.raygun4java.core.messages.RaygunEnvironmentMessage <init>
2019-04-07T18:05:36.006445+00:00 app[worker.1]: INFO: Couldn't access all environment data. If you are running in GAE or a restricted environment this is expected
2019-04-07T18:05:36.006447+00:00 app[worker.1]: java.awt.HeadlessException: 
2019-04-07T18:05:36.006449+00:00 app[worker.1]: No X11 DISPLAY variable was set, but this program performed an operation which requires it.
2019-04-07T18:05:36.006450+00:00 app[worker.1]: 	at sun.java2d.HeadlessGraphicsEnvironment.getMaximumWindowBounds(HeadlessGraphicsEnvironment.java:85)
2019-04-07T18:05:36.006452+00:00 app[worker.1]: 	at com.mindscapehq.raygun4java.core.messages.RaygunEnvironmentMessage.<init>(RaygunEnvironmentMessage.java:46)
2019-04-07T18:05:36.006453+00:00 app[worker.1]: 	at com.mindscapehq.raygun4java.core.RaygunMessageBuilder.SetEnvironmentDetails(RaygunMessageBuilder.java:47)
2019-04-07T18:05:36.006455+00:00 app[worker.1]: 	at com.fatboyindustrial.raygun.RaygunAppender.append(RaygunAppender.java:97)
2019-04-07T18:05:36.006457+00:00 app[worker.1]: 	at com.fatboyindustrial.raygun.RaygunAppender.append(RaygunAppender.java:51)
2019-04-07T18:05:36.006458+00:00 app[worker.1]: 	at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
2019-04-07T18:05:36.006459+00:00 app[worker.1]: 	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
2019-04-07T18:05:36.006461+00:00 app[worker.1]: 	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
2019-04-07T18:05:36.006462+00:00 app[worker.1]: 	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
2019-04-07T18:05:36.006464+00:00 app[worker.1]: 	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
2019-04-07T18:05:36.006465+00:00 app[worker.1]: 	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
2019-04-07T18:05:36.006467+00:00 app[worker.1]: 	at ch.qos.logback.classic.Logger.warn(Logger.java:692)
2019-04-07T18:05:36.006468+00:00 app[worker.1]: 	at reactor.util.Loggers$Slf4JLogger.warn(Loggers.java:299)
2019-04-07T18:05:36.006470+00:00 app[worker.1]: 	at discord4j.command.CommandBootstrapper.lambda$static$0(CommandBootstrapper.java:49)
2019-04-07T18:05:36.006471+00:00 app[worker.1]: 	at discord4j.command.util.AbstractCommandDispatcher.lambda$null$4(AbstractCommandDispatcher.java:66)
2019-04-07T18:05:36.006472+00:00 app[worker.1]: 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
2019-04-07T18:05:36.006474+00:00 app[worker.1]: 	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:358)
2019-04-07T18:05:36.006475+00:00 app[worker.1]: 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134)
2019-04-07T18:05:36.006477+00:00 app[worker.1]: 	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:358)
2019-04-07T18:05:36.006479+00:00 app[worker.1]: 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:1747)
2019-04-07T18:05:36.006480+00:00 app[worker.1]: 	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:358)
2019-04-07T18:05:36.006481+00:00 app[worker.1]: 	at reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1550)
2019-04-07T18:05:36.006482+00:00 app[worker.1]: 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreInner.onError(MonoIgnoreThen.java:235)
2019-04-07T18:05:36.006484+00:00 app[worker.1]: 	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onError(FluxContextStart.java:117)
2019-04-07T18:05:36.006485+00:00 app[worker.1]: 	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:358)
2019-04-07T18:05:36.006487+00:00 app[worker.1]: 	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:184)
2019-04-07T18:05:36.006488+00:00 app[worker.1]: 	at reactor.core.scheduler.ElasticScheduler$DirectScheduleTask.run(ElasticScheduler.java:291)
2019-04-07T18:05:36.006490+00:00 app[worker.1]: 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
2019-04-07T18:05:36.006491+00:00 app[worker.1]: 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
2019-04-07T18:05:36.006493+00:00 app[worker.1]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-04-07T18:05:36.006495+00:00 app[worker.1]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2019-04-07T18:05:36.006496+00:00 app[worker.1]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2019-04-07T18:05:36.006497+00:00 app[worker.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-04-07T18:05:36.006499+00:00 app[worker.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-04-07T18:05:36.006501+00:00 app[worker.1]: 	at java.lang.Thread.run(Thread.java:748)
2019-04-07T18:05:36.006502+00:00 app[worker.1]: `

**Comment by gkopff** [comment]
> INFO: Couldn't access all environment data. If you are running in GAE or a restricted environment this is expected 2019-04-07T18:05:36.006447+00:00 app[worker.1]: java.awt.HeadlessException: 2019-04-07T18:05:36.006449+00:00 app[worker.1]: No X11 DISPLAY variable was set, but this program performed an operation which requires it.

I believe that is internal to the Raygun classes, but also harmless - as it says it is expected in a headless environment.
